### ISSUE TITLE
Cannot load the Part Module in Python

### ISSUE THREAD

**Issue by wassimj** [infeeeee/DynFreeCAD#2]
Hello,
Everything is installed (Dynamo 2.8, FC 0.19 with python 3.8 etc) and seems running well except the example "UseTheApi.dyn" is reporting that the Part module could not be loaded. I have specified the correct FreeCADBinPath (on my computer it is C:\Program Files\FreeCAD 0.19\bin).
Also, as you see in the second image below, if I simply short-circuit the python script and simply save the newly created document, it does so correctly (obviously with no geometry in it).
What am I missing to enable Dynamo Python to find the 'Part' module?
![ErrorScreenShot](https://user-images.githubusercontent.com/6302909/93047185-8f538780-f664-11ea-842c-c38c17f2fcad.png)
![image](https://user-images.githubusercontent.com/6302909/93047352-fcffb380-f664-11ea-80b6-fb9dc45e5b8c.png)

**Comment by infeeeee** [comment]
Hello
I already had this issue, and asked about it on the dynamo forum, as I guess it's a bug in dynamo:

https://forum.dynamobim.com/t/how-to-use-import-from-custom-path-in-multiple-cpython-blocks/55071/3

You can see the solution on that thread: Create a new graph, import the required submodules, close the graph, then open this or any other graph, now you can import any FreeCAD submodules successfully.

I added this loader graph to the [examples folder](https://github.com/infeeeee/DynFreeCAD/tree/master/Examples): ApiLoader.dyn. This imports most of the FreeCAD libs and mods.

So all steps of the workaround, I will add this to readme or inside a node if they can't help me on dynamo forum:

1. Close Dynamo
2. Open Dynamo
3. Open ApiLoader.dyn
4. Run, if no errors given then close the graph, (not dynamo! just the graph)
5. Open UseTheApi or create new FreeCAD graphs, every node should work.

**Comment by infeeeee** [comment]
I added every info from this thread to the readme, so I close this issue.
