### ISSUE TITLE
What am i doing wrong?

### ISSUE THREAD

**Issue by nortikin** [infeeeee/DynFreeCAD#3]
![image](https://user-images.githubusercontent.com/5783432/93485567-de6f1600-f90b-11ea-9a2e-f2643c7970b6.png)
trying to run, but it cannot
![image](https://user-images.githubusercontent.com/5783432/93485677-fd6da800-f90b-11ea-9dca-53f60bb99bdc.png)

**Comment by nortikin** [comment]
oh, i see, i need conda, not an freecad itself

**Comment by infeeeee** [comment]
The python version is the only one that matters. The only prebuilt with python 3.8.x I found is linked in the readme, please use that version. If you want to use it with 0.18, you have to build it yourself.
You can check the python version of the build with this commands in FreeCAD's python console:
```python
import sys
sys.version
```
The main version has to be the same as in dynamo.
